name: dengue_tcc
description: Flutter project to TCC graduation

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  another_flushbar: ^1.12.29
  awesome_dialog: ^3.0.0
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_analytics: ^10.0.2
  firebase_core: ^2.1.0
  firebase_crashlytics: ^3.0.2
  firebase_remote_config: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_map: ^3.0.0
  flutter_modular: ^5.0.3
  flutter_svg: ^1.1.0
  geolocator: ^9.0.1
  latlong2: ^0.8.1
  mask_text_input_formatter: ^2.4.0
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  validatorless: ^1.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.3+1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
